import { request, ResolvableResource } from './common.ts'

export const tickle = (): ResolvableResource => request('/img/tickle')
export const slap = (): ResolvableResource => request('/img/slap')
export const poke = (): ResolvableResource => request('/img/poke')
export const pat = (): ResolvableResource => request('/img/pat')
export const neko = (): ResolvableResource => request('/img/neko')
export const meow = (): ResolvableResource => request('/img/meow')
export const lizard = (): ResolvableResource => request('/img/lizard')
export const kiss = (): ResolvableResource => request('/img/kiss')
export const hug = (): ResolvableResource => request('/img/hug')
export const foxGirl = (): ResolvableResource => request('/img/fox_girl')
export const feed = (): ResolvableResource => request('/img/feed')
export const cuddle = (): ResolvableResource => request('/img/cuddle')
export const why = (): Promise<{ why: string }> => request('/why')
export const catText = (): Promise<{ cat: string }> => request('/cat')
export const OwOify = (text: string): Promise<{ owo: string }> => request('/owoify?text='+encodeURIComponent(text))
export const eightBall = (): Promise<{ response: string, url: string }> => request('/8ball')
export const fact = (): Promise<{ fact: string }> => request('/fact')
export const nekoGif = (): ResolvableResource => request('/img/ngif')
export const kemonomimi = (): ResolvableResource => request('/img/kemonomimi')
export const holo = (): ResolvableResource => request('/img/holo')
export const smug = (): ResolvableResource => request('/img/smug')
export const baka = (): ResolvableResource => request('/img/baka')
export const woof = (): ResolvableResource => request('/img/woof')
export const spoiler = (): ResolvableResource => request('/spoiler')
export const wallpaper = (): ResolvableResource => request('/img/wallpaper')
export const goose = (): ResolvableResource => request('/img/goose')
export const gecg = (): ResolvableResource => request('/img/gecg')
export const avatar = (): ResolvableResource => request('/img/avatar')
export const waifu = (): ResolvableResource => request('/img/waifu')